type Lang="en"|"ru";
const copy={
 en:{nav:["Collection","Manifesto","Stockists"],menu:"MENU ☰",issue:"ISSUE N°07",title:<>FORM<br/><i>FOLLOWS</i><br/>FEELING.</>,caption:<>AUTUMN / WINTER<br/>A STUDY IN SILHOUETTE</>,discover:"DISCOVER THE EDIT →",vertical:"INDEPENDENT FASHION HOUSE",manifest:<>We make clothes for the space<br/>between <em>presence</em> and <em>absence.</em></>,selected:"(02) SELECTED LOOKS",season:"AW / 26",collectionLead:"Three studies in engineered volume, cut from deadstock wool and technical silk.",looks:["STRUCTURE / 01","VOID / 02","MOTION / 03"],view:"VIEW LOOK ↗",quote:<>NO TREND.<br/>NO SEASON.<br/><i>ONLY FORM.</i></>,quoteLabel:"THE NOIR MANIFESTO / 2026"},
 ru:{nav:["Коллекция","Манифест","Магазины"],menu:"МЕНЮ ☰",issue:"ВЫПУСК N°07",title:<>ФОРМА<br/><i>СЛЕДУЕТ</i><br/>ЧУВСТВУ.</>,caption:<>ОСЕНЬ / ЗИМА<br/>ИССЛЕДОВАНИЕ СИЛУЭТА</>,discover:"СМОТРЕТЬ РЕДАКЦИЮ →",vertical:"НЕЗАВИСИМЫЙ ДОМ МОДЫ",manifest:<>Мы создаём одежду для пространства<br/>между <em>присутствием</em> и <em>отсутствием.</em></>,selected:"(02) ИЗБРАННЫЕ ОБРАЗЫ",season:"ОЗ / 26",collectionLead:"Три исследования выверенного объёма из архивной шерсти и технического шёлка.",looks:["СТРУКТУРА / 01","ПУСТОТА / 02","ДВИЖЕНИЕ / 03"],view:"СМОТРЕТЬ ОБРАЗ ↗",quote:<>БЕЗ ТРЕНДА.<br/>БЕЗ СЕЗОНА.<br/><i>ТОЛЬКО ФОРМА.</i></>,quoteLabel:"МАНИФЕСТ NOIR / 2026"}
} as const;
export function SiteHome({lang}:{lang:Lang}){const c=copy[lang],prefix=lang==="ru"?"/ru":"/en";return <main data-lang={lang}><div className="lang-float"><a className={lang==="en"?"active":""} href="/">EN</a><a className={lang==="ru"?"active":""} href="/ru">RU</a></div><nav><a className="logo" href="#top">ATELIER<br/>NOIR</a><div><a href={`${prefix}/collection`}>{c.nav[0]}</a><a href={`${prefix}/manifesto`}>{c.nav[1]}</a><a href="#contact">{c.nav[2]}</a></div><SiteMenu lang={lang}/></nav>
 <section className="hero" id="top"><div className="issue">{c.issue} <span>PARIS / 2026</span></div><h1>{c.title}</h1><div className="figure" aria-hidden="true"><div className="head"/><div className="body"/></div><p className="caption">{c.caption}</p><a className="discover" href="#collection">{c.discover}</a><div className="vertical">{c.vertical}</div></section>
 <section className="manifesto" id="manifesto"><span>(01)</span><p>{c.manifest}</p><small>PARIS — TOKYO<br/>EST. 2018</small></section><section className="collection" id="collection"><div className="head"><span>{c.selected}</span><h2>{c.season}</h2><p>{c.collectionLead}</p></div><div className="looks">{c.looks.map((look,i)=><article className={`look l${i+1}`} key={look}><div className="silhouette"><i/><b/></div><span>{look}</span><a href="#contact">{c.view}</a></article>)}</div></section><section className="quote"><p>{c.quote}</p><span>{c.quoteLabel}</span></section><footer id="contact"><a className="logo" href="#top">ATELIER NOIR</a><p>41 RUE DE SAINTONGE<br/>75003 PARIS</p><a href="mailto:studio@noir.example">STUDIO@NOIR.PARIS ↗</a></footer></main>}
import { SiteMenu } from "./SiteMenu";
