type Lang="en"|"ru";
const content={
 en:{brand:"ATELIER NOIR",back:"Back to index",switchTo:"/ru",switchLabel:"RU",title:"An archive of form.",lead:"Objects, garments and ideas from the space between presence and absence.",pages:{
  collection:{label:"Collection",eyebrow:"AUTUMN / WINTER 2026",title:"Engineered volume.",intro:"A collection in deadstock wool and technical silk, constructed around movement rather than trend.",cards:[["Structure / 01","Double-faced wool coat with a suspended shoulder."],["Void / 02","Bias-cut silk column with an open architectural back."],["Motion / 03","Technical parka built from one continuous pattern."]],note:"Made in Paris in editions of twenty."},
  manifesto:{label:"Manifesto",eyebrow:"NO TREND / NO SEASON",title:"Only form remains.",intro:"We reject accelerated seasons and design clothing to gather history, not become it.",cards:[["Material first","Deadstock and traceable natural fibers define the cut."],["Human scale","Every piece is finished by one atelier team."],["Permanent study","Forms return, evolve and remain repairable."]],note:"Atelier Noir, Paris — established 2018."}
 }},
 ru:{brand:"ATELIER NOIR",back:"К оглавлению",switchTo:"/",switchLabel:"EN",title:"Архив формы.",lead:"Объекты, одежда и идеи из пространства между присутствием и отсутствием.",pages:{
  collection:{label:"Коллекция",eyebrow:"ОСЕНЬ / ЗИМА 2026",title:"Спроектированный объём.",intro:"Коллекция из архивной шерсти и технического шёлка, построенная вокруг движения, а не тренда.",cards:[["Структура / 01","Двустороннее пальто с подвешенной линией плеча."],["Пустота / 02","Шёлковая колонна по косой с открытой спиной."],["Движение / 03","Техническая парка из одной непрерывной выкройки."]],note:"Произведено в Париже сериями по двадцать экземпляров."},
  manifesto:{label:"Манифест",eyebrow:"БЕЗ ТРЕНДА / БЕЗ СЕЗОНА",title:"Остаётся только форма.",intro:"Мы отказываемся от ускоренных сезонов и создаём одежду, которая собирает историю, а не становится ею.",cards:[["Сначала материал","Архивные и отслеживаемые волокна определяют крой."],["Человеческий масштаб","Каждую вещь завершает одна команда ателье."],["Постоянное исследование","Формы возвращаются, развиваются и ремонтируются."]],note:"Atelier Noir, Париж — основано в 2018 году."}
 }}} as const;
export function LocalizedLanding({lang}:{lang:Lang}){const c=content[lang];return <main className="locale-home"><header><a href="/">{c.brand}</a><a href={c.switchTo}>{c.switchLabel}</a></header><section><p>{lang==="ru"?"ПАРИЖ / АРХИВ 07":"PARIS / ARCHIVE 07"}</p><h1>{c.title}</h1><span>{c.lead}</span><div>{Object.entries(c.pages).map(([s,p])=><a key={s} href={`/${lang}/${s}`}>{p.label} ↗</a>)}</div></section></main>}
export function DetailPage({lang,slug}:{lang:Lang;slug:string}){const c=content[lang];const p=c.pages[slug as keyof typeof c.pages]||c.pages.collection;const home=lang==="ru"?"/ru":"/";return <main className="inner-page" data-lang={lang}><div className="lang-float"><a className={lang==="en"?"active":""} href={`/en/${slug}`}>EN</a><a className={lang==="ru"?"active":""} href={`/ru/${slug}`}>RU</a></div><nav className="inner-site-nav"><a className="logo" href={home}>ATELIER<br/>NOIR</a><div>{Object.entries(c.pages).map(([s,v])=><a key={s} href={`/${lang}/${s}`}>{v.label}</a>)}<a href={`${home}#contact`}>{lang==="ru"?"Контакты":"Contact"}</a></div><SiteMenu lang={lang}/></nav><section className="inner-hero"><p>{p.eyebrow}</p><h1>{p.title}</h1><span>{p.intro}</span></section><section className="inner-cards">{p.cards.map(([t,d],i)=><article key={t}><small>({i+1})</small><div className="mini-figure"/><h2>{t}</h2><p>{d}</p></article>)}</section><footer><p>{p.note}</p><a href={home}>{c.back} ↑</a></footer></main>}
import { SiteMenu } from "./SiteMenu";
